In [ ]:
# 뉴욕타임스 기사의 일부 headline을 읽어 단어 단위 텍스트 생성 모델 작성
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/pykwon/python/master/testdata_utf8/articlesapril.csv")
print(df.head(3))
print(df.count)
print(df['headline'])

print(df['headline'].isnull().values.any())
print(df.headline.values)

headline=[]
headline.extend(list(df.headline.values))
print(headline[:10])
print(len(headline))  # 1324
if 'Unknown' in headline:print('Unknown 발견')
headline = [n for n in headline if n != 'Unknown']
print(len(headline))  # 1214
print(headline[:10])

                  articleID  articleWordCount            byline documentType  \
0  5adf6684068401528a2aa69b               781    By JOHN BRANCH      article   
1  5adf653f068401528a2aa697               656  By LISA FRIEDMAN      article   
2  5adf4626068401528a2aa628              2427     By PETE WELLS      article   

                                            headline  \
0  Former N.F.L. Cheerleaders’ Settlement Offer: ...   
1  E.P.A. to Unveil a New Rule. Its Effect: Less ...   
2                            The New Noma, Explained   

                                            keywords  multimedia  newDesk  \
0  ['Workplace Hazards and Violations', 'Football...          68   Sports   
1  ['Environmental Protection Agency', 'Pruitt, S...          68  Climate   
2  ['Restaurants', 'Noma (Copenhagen, Restaurant)...          66   Dining   

   printPage              pubDate   sectionName  \
0          0  2018-04-24 17:16:49  Pro Football   
1          0  2018-04-24 17:11:21       Unk

In [ ]:
# print('Ho하이llo 가a나다'.encode("ascii",errors="ignore").decode())
from string import punctuation
# print(", py'thon,!".strip(punctuation))
# print(", py'thon,!".strip(punctuation + ' '))

def repreFunc(s): # 다 소문자로 바꾸고, 점이나 다른 문자 빼기
  s = s.encode("utf-8").decode("ascii",errors="ignore")
  return ''.join(c for c in s if c not in punctuation).lower()

text = [repreFunc(ss) for ss in headline]
print(text[:10])


['former nfl cheerleaders settlement offer 1 and a meeting with goodell', 'epa to unveil a new rule its effect less science in policymaking', 'the new noma explained', 'how a bag of texas dirt  became a times tradition', 'is school a place for selfexpression', 'commuter reprogramming', 'ford changed leaders looking for a lift its still looking', 'romney failed to win at utah convention but few believe hes doomed', 'chain reaction', 'he forced the vatican to investigate sex abuse now hes meeting with pope francis']


In [ ]:
from keras.preprocessing.text import Tokenizer
tok = Tokenizer()
tok.fit_on_texts(text)
print(tok.word_index)
vocab_size = len(tok.word_index) + 1
print('단어사전(집합)의 크기 : %d'%vocab_size)

sequences = list()
for line in text:
  enc = tok.texts_to_sequences([line])[0]
  for i in range(1, len(enc)):
    se = enc[:i+1]
    sequences.append(se)
# print(sequences)
print(sequences[:5])
# ['Former N.F.L. Cheerleaders’ Settlement Offer: $1 and a Meeting With Goodell' ...
# [[99, 269], [99, 269, 371], [99, 269, 371, 1115], [99, 269, 371, 1115, 582], ...

{'the': 1, 'a': 2, 'to': 3, 'of': 4, 'in': 5, 'for': 6, 'and': 7, 'is': 8, 'on': 9, 'with': 10, 'trump': 11, 'as': 12, 'at': 13, 'new': 14, 'how': 15, 'from': 16, 'it': 17, 'an': 18, 'that': 19, 'be': 20, 'season': 21, 'us': 22, 'you': 23, 'its': 24, 'what': 25, 'episode': 26, 'can': 27, 'your': 28, 'not': 29, 'he': 30, 'now': 31, 'his': 32, 'are': 33, 'teaching': 34, 'war': 35, 'out': 36, 'no': 37, 'was': 38, 'by': 39, 'trumps': 40, 'has': 41, 'over': 42, 'may': 43, 'into': 44, 'why': 45, 'more': 46, 'we': 47, 'who': 48, 'about': 49, 'recap': 50, 'activities': 51, '1': 52, 'just': 53, 'do': 54, 'women': 55, 'when': 56, 'syria': 57, 'trade': 58, 'i': 59, '2': 60, 'or': 61, 'will': 62, 'this': 63, 'have': 64, 'president': 65, 'but': 66, 'home': 67, 'up': 68, 'long': 69, 'one': 70, 'off': 71, 'facebook': 72, 'house': 73, 'gop': 74, 'our': 75, 'case': 76, 'they': 77, 'life': 78, 'end': 79, 'right': 80, 'some': 81, 'big': 82, 'dead': 83, 'power': 84, 'say': 85, 'white': 86, 'after': 87, 's

In [ ]:
print('dict items : ',tok.word_index.items())
index_to_word = {}
for key, value in tok.word_index.items():
  index_to_word[value] = key
print(index_to_word)
print(index_to_word[371])
print(index_to_word[1115])

max_len = max(len(i) for i in sequences)
print('배열 요소 값 중 최대 : ',max_len) # headline 중 가장 긴 단어들로 구성된 최대 수치

dict items :  dict_items([('the', 1), ('a', 2), ('to', 3), ('of', 4), ('in', 5), ('for', 6), ('and', 7), ('is', 8), ('on', 9), ('with', 10), ('trump', 11), ('as', 12), ('at', 13), ('new', 14), ('how', 15), ('from', 16), ('it', 17), ('an', 18), ('that', 19), ('be', 20), ('season', 21), ('us', 22), ('you', 23), ('its', 24), ('what', 25), ('episode', 26), ('can', 27), ('your', 28), ('not', 29), ('he', 30), ('now', 31), ('his', 32), ('are', 33), ('teaching', 34), ('war', 35), ('out', 36), ('no', 37), ('was', 38), ('by', 39), ('trumps', 40), ('has', 41), ('over', 42), ('may', 43), ('into', 44), ('why', 45), ('more', 46), ('we', 47), ('who', 48), ('about', 49), ('recap', 50), ('activities', 51), ('1', 52), ('just', 53), ('do', 54), ('women', 55), ('when', 56), ('syria', 57), ('trade', 58), ('i', 59), ('2', 60), ('or', 61), ('will', 62), ('this', 63), ('have', 64), ('president', 65), ('but', 66), ('home', 67), ('up', 68), ('long', 69), ('one', 70), ('off', 71), ('facebook', 72), ('house', 73)

In [ ]:
from keras.utils import pad_sequences
psequences = pad_sequences(sequences, maxlen=max_len, padding='pre')
print(psequences[:3])

import numpy as np
psequences = np.array(psequences)
x = psequences[:, :-1] # feature
y = psequences[:, -1] # label
print(x[:3])
print(y[:3])

# y(label)는 원핫 처리
from keras.utils import to_categorical
y = to_categorical(y, num_classes=vocab_size)
print(y[:3])

[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0   99  269]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0   99  269  371]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0   99  269  371 1115]]
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0  99]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0  99 269]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0  99 269 371]]
[ 269  371 1115]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
from keras.layers import Embedding, Dense, LSTM, Flatten
from keras.models import Sequential
model = Sequential()
model.add(Embedding(vocab_size, 32, input_length=max_len-1)) # 정수 인덱싱을 밀집벡터로 매핑
model.add(LSTM(128, activation='tanh'))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(vocab_size, activation='softmax'))
print(model.summary())

model.compile(optimizer='adam',loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(x, y, epochs=200, verbose=2, batch_size=32)
print(model.evaluate(x,y))


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 23, 32)            111808    
                                                                 
 lstm (LSTM)                 (None, 128)               82432     
                                                                 
 flatten (Flatten)           (None, 128)               0         
                                                                 
 dense (Dense)               (None, 128)               16512     
                                                                 
 dense_1 (Dense)             (None, 3494)              450726    
                                                                 
Total params: 661478 (2.52 MB)
Trainable params: 661478 (2.52 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None
Epoch 1/200
244


KeyboardInterrupt



In [ ]:
# 문장 생성을 위한 함수
def textGenerationFunc(model, tok, seed_word, n):
  init_word = seed_word
  sentence = ''
  for _ in range(n):
    encoded = tok.texts_to_sequences([seed_word])[0]
    encoded = pad_sequences([encoded], maxlen=max_len - 1, padding='pre')
    result = np.argmax(model.predict(encoded, verbose=0), axis=-1)
    # 예측 단어 찾기
    for word, index in tok.word_index.items():
      # print(word, index)
      if index == result:   # 예측한 단어의 인덱스와 동일한 단어가 있다면
        break   # 해당 단어가 예측단어 이므로 break

    seed_word = seed_word + ' ' + word
    sentence = sentence + ' ' + word
  sentence = init_word + sentence
  return sentence

print(textGenerationFunc(model, tok, 'the', 10))
print(textGenerationFunc(model, tok, 'the', 100))
print(textGenerationFunc(model, tok, 'changed leaders looking', 50))